version: 2
jobs:
  build:
    docker:
      - image: starefossen/ruby-node:2-8

    working_directory: ~/repo

    environment:
      - BUNDLE_PATH: /root/project

    steps:
      - checkout

      - restore_cache:
          keys:
            - v4-dependencies-{{ checksum "Gemfile.lock" }}
            - v4-dependencies-

      - run:
          name: Ruby dependencies
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - vendor/bundle
          key: v4-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: Build
          command: bundle exec jekyll build --verbose

     # - run:
     #     name: Test
     #     command: bundle exec htmlproofer ./_site --check-html

      - persist_to_workspace:
          root: .
          paths:
            - _site
  deploy:
    machine:
      enabled: true
    steps:
      - attach_workspace:
          at: workspace
      - run:
          name: Rsync
          command: rsync -azv --delete -e "ssh" workspace/_site/ $SSH_USER@$SSH_HOST:/home/$SSH_USER/public_html

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
