version: 2
jobs:
  build:
    docker:
      - image: starefossen/ruby-node:2-8

    working_directory: ~/repo

    environment:
      - BUNDLE_PATH: /root/project

    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "Gemfile.lock" }}
            - v2-dependencies-

      - run:
          name: Ruby dependencies
          command: bundle install

      - save_cache:
          paths:
            - /usr/local/bundle
            - /usr/local/lib/node_modules
          key: v2-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: Build
          command: bundle exec jekyll build --verbose
      
     # - run:
     #     name: Test
     #     command: bundle exec htmlproofer ./_site --check-html
