version: 2
jobs:
  build:
    docker:
      - image: jekyll/builder
    environment:
      - BUNDLE_PATH: ~/repo/vendor/bundle
    steps:
      - checkout
      - run: bundle check || bundle install
      - run: bundle exec jekyll build
